PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true
    Template:
      Count: 3
      Start: 0
      SANS:
        - 10.125.178.58
        - 10.125.176.96
        - 10.125.178.62
        - peer0.org1.example.com
        - peer1.org1.example.com
        - peer2.org1.example.com
    Users:
      Count: 1