PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true
    Template:
      Count: 3
      Start: 0
      SANS:
        - # -> IP addresses or DNS hostnames of each peer
        - # -> IP addresses or DNS hostnames of each peer
        - # -> IP addresses or DNS hostnames of each peer
      Hostname: {{.Prefix}}{{.Index}}
    Users:
      Count: 1
