PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true
    Template:
      Count: 3
      Start: 0
      SANS:
        - 10.125.169.93
        - 10.125.169.12
        - 10.125.169.6
        - org1.example.com
    Users:
      Count: 1