peer:
  id: peer1.org1.example.com
  networkId: dev
  listenAddress: 0.0.0.0:8051
  address: 10.125.176.96:8051
  addressAutoDetect: false
  gateway:
    enabled: true
    endorsementTimeout: 30s
    broadcastTimeout: 30s
    dialTimeout: 2m
  keepalive:
    interval: 7200s
    timeout: 20s
    minInterval: 60s
    client:
      interval: 60s
      timeout: 20s
    deliveryClient:
      interval: 60s
      timeout: 20s
  gossip:
    bootstrap: 10.125.178.62:9051
    useLeaderElection: false
    orgLeader: true
    membershipTrackerInterval: 5s
    endpoint: 10.125.176.96:8051
    maxBlockCountToStore: 10
    maxPropagationBurstLatency: 10ms
    maxPropagationBurstSize: 10
    propagateIterations: 1
    propagatePeerNum: 3
    pullInterval: 4s
    pullPeerNum: 3
    requestStateInfoInterval: 4s
    publishStateInfoInterval: 4s
    stateInfoRetentionInterval:
    publishCertPeriod: 10s
    skipBlockVerification: false
    dialTimeout: 3s
    connTimeout: 2s
    recvBuffSize: 20
    sendBuffSize: 200
    digestWaitTime: 1s
    requestWaitTime: 1500ms
    responseWaitTime: 2s
    aliveTimeInterval: 5s
    aliveExpirationTimeout: 25s
    reconnectInterval: 25s
    maxConnectionAttempts: 120
    msgExpirationFactor: 20
    externalEndpoint: 10.125.176.96:8051
    election:
      startupGracePeriod: 15s
      membershipSampleInterval: 1s
      leaderAliveThreshold: 10s
      leaderElectionDuration: 5s
    pvtData:
      pullRetryThreshold: 60s
      transientstoreMaxBlockRetention: 1000
      pushAckTimeout: 3s
      btlPullMargin: 10
      reconcileBatchSize: 10
      reconcileSleepInterval: 1m
      reconciliationEnabled: true
      skipPullingInvalidTransactionsDuringCommit: false
      implicitCollectionDisseminationPolicy:
        requiredPeerCount: 0
        maxPeerCount: 1
    state:
      enabled: false
      checkInterval: 10s
      responseTimeout: 3s
      batchSize: 10
      blockBufferSize: 20
      maxRetries: 3
  tls:
    enabled: true
    clientAuthRequired: false
    cert:
      file: ../network/organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/server.crt
    key:
      file: ../network/organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/server.key
    rootcert:
      file: ../network/organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/ca.crt
    clientRootCAs:
      files:
        - ../network/organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/ca.crt
    clientKey:
      file: ../network/organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/server.key
    clientCert:
      file: ../network/organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/server.crt
  authentication:
    timewindow: 15m
  fileSystemPath: ./production
  BCCSP:
    Default: SW
    SW:
      Hash: SHA2
      Security: 256
      FileKeyStore:
        KeyStore:
    PKCS11:
      Library:
      Label:
      Pin:
      Hash:
      Security:
      SoftwareVerify:
      Immutable:
      AltID:
      KeyIds:
  mspConfigPath: ../network/organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp
  localMspId: Org1MSP
  client:
    connTimeout: 3s
  deliveryclient:
    blockGossipEnabled: true
    reconnectTotalTimeThreshold: 3600s
    connTimeout: 3s
    reConnectBackoffThreshold: 3600s
    addressOverrides:
  localMspType: bccsp
  profile:
    enabled:     false
    listenAddress: 0.0.0.0:6060
  handlers:
    authFilters:
      -
        name: DefaultAuth
      -
        name: ExpirationCheck    
    decorators:
      -
        name: DefaultDecorator
    endorsers:
      escc:
        name: DefaultEndorsement
        library:
    validators:
      vscc:
        name: DefaultValidation
        library:
  validatorPoolSize:
  discovery:
    enabled: true
    authCacheEnabled: true
    authCacheMaxSize: 1000
    authCachePurgeRetentionRatio: 0.75
    orgMembersAllowedAccess: false
  limits:
    concurrency:
      endorserService: 2500
      deliverService: 2500
      gatewayService: 500
  maxRecvMsgSize: 104857600
  maxSendMsgSize: 104857600
vm:
  endpoint: unix:///var/run/docker.sock
  docker:
    tls:
      enabled: false
      ca:
        file: docker/ca.crt
      cert:
        file: docker/tls.crt
      key:
        file: docker/tls.key
    attachStdout: false
    hostConfig:
      NetworkMode: host
      Dns:
      LogConfig:
        Type: json-file
        Config:
          max-size: "50m"
          max-file: "5"
      Memory: 2147483648
chaincode:
  id:
    path:
    name:
  builder: hyperledger/fabric-ccenv:2.5
  pull: false
  golang:
    runtime: hyperledger/fabric-baseos:2.5
    dynamicLink: false
  externalBuilders:
    - name: golang
      path: /opt/hyperledger/externalbuilders/golang
      propagateEnvironment:
        - GOPROXY
        - GONOPROXY
        - GOSUMDB
        - GONOSUMDB
  installTimeout: 300s
  startuptimeout: 300s
  executetimeout: 30s
  mode: net
  keepalive: 0
  system:
    _lifecycle: enable
    cscc: enable
    lscc: enable
    qscc: enable
  logging:
    level:  debug
    shim:   warning
    format: '%{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc} -> %{level:.4s} %{id:03x}%{color:reset} %{message}'
ledger:
  blockchain:
  state:
    stateDatabase: goleveldb
    totalQueryLimit: 100000
  history:
    enableHistoryDatabase: true
  pvtdataStore:
    collElgProcMaxDbBatchSize: 5000
    collElgProcDbBatchesInterval: 1000
    deprioritizedDataReconcilerInterval: 60m
    purgeInterval: 100
    purgedKeyAuditLogging: true
  snapshots:
    rootDir: /home/worker2/Documents/ai-driven-sc-opt-fw/config/production/snapshots
operations:
  listenAddress: 127.0.0.1:9443
  tls:
    enabled: false
    cert:
      file:
    key:
      file:
    clientAuthRequired: false
    clientRootCAs:
      files: []
metrics:
  provider: disabled
  statsd:
    network: udp
    address: 127.0.0.1:8125
    writeInterval: 10s
    prefix: