peer:
  id: peer1.org1.example.com
  networkId: dev
  listenAddress: 192.168.1.11:8051
  address: 192.168.1.11:8051
  addressAutoDetect: false
  gateway:
    enabled: true
  gossip:
    bootstrap: 192.168.1.12:9051
    useLeaderElection: false
    orgLeader: true
    externalEndpoint: 192.168.1.11:8051
  tls:
    enabled: false
  fileSystemPath: /data/peer1
  mspConfigPath: /data/peer1/msp
  localMspId: Org1MSP
  localMspType: bccsp

chaincode:
  mode: dev
  logging:
    level: info
    shim: warning

ledger:
  state:
    stateDatabase: goleveldb
  history:
    enableHistoryDatabase: true

operations:
  listenAddress: 192.168.1.11:9543

metrics:
  provider: disabled
