peer:
  id: peer2.org1.example.com
  networkId: dev
  listenAddress: 192.168.1.12:9051
  address: 192.168.1.12:9051
  addressAutoDetect: false
  gateway:
    enabled: true
  gossip:
    bootstrap: 192.168.1.10:7051
  gossip:
    useLeaderElection: false
    orgLeader: true
    externalEndpoint: 192.168.1.12:9051
  tls:
    enabled: false
  fileSystemPath: /data/peer2
  mspConfigPath: /data/peer2/msp
  localMspId: Org1MSP
  localMspType: bccsp

chaincode:
  mode: dev
  logging:
    level: info
    shim: warning

ledger:
  state:
    stateDatabase: goleveldb
  history:
    enableHistoryDatabase: true

operations:
  listenAddress: 192.168.1.12:9643

metrics:
  provider: disabled
